global:
  resolve_timeout: 5m
  slack_api_url: "https://hooks.slack.com/services/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"

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 18h
  receiver: 'slack-notifications'

receivers:
  - name: "slack-notifications"
    slack_configs:
      - channel: "#monitoring-shopify-apps"
        send_resolved: true
        title_link: https://grafana.functor.dev
        icon_emoji: ":rocket:"
        title: |-
          {{ if eq .Status "firing" }}:rotating_light: Monitor triggered{{ end }}{{ if eq .Status "resolved" }}:sunglasses: Monitor resolved{{ end }}: {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.summary }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ if or (eq .Labels.severity "critical") (eq .Labels.severity "page") }} *Attention:* <@U0566P7UF1Q> <@U03T2BB2Q6M> <@U7TRL8XSQ> {{ end }}
          {{ end }}