global:
  scrape_interval: 30s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 30s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
    monitor: "shopify-react-router-v7-boilerplate"

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: "shopify-react-router-v7-boilerplate"
    static_configs:
      - targets: ["docker.for.mac.host.internal:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["docker.for.mac.host.internal:19101"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: (node-exporter:9100)
        replacement: "shopify-server"
      - source_labels: [ __address__ ]
        target_label: instance
        regex: (127.0.0.1:9100)
        replacement: "shopify-server"

  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "docker.for.mac.host.internal:19102"